apiVersion: v1
kind: Namespace
metadata:
  name: hfghfgh-staging
  labels:
    environment-id: env_e56cb113-269b-4edb-a1ca-6e9dc0e052ae
    project-id: project_eb2387c9-f3fa-4575-b002-d98309e3fcfb
    project-name: hfghfgh
    environment-name: staging
    organization-id: org_c50d7b26-1f2a-4a6e-b11e-469a86e002c8
