apiVersion: v1
kind: Namespace
metadata:
  name: adasddsasdasd-dev
  labels:
    environment-id: env_6742eb7b-af4c-414d-b96b-01e03cfd53e0
    project-id: project_dbf3be21-ab20-4406-9a69-7f8c4a4aa45e
    project-name: adasddsasdasd
    environment-name: dev
    organization-id: org_c50d7b26-1f2a-4a6e-b11e-469a86e002c8
